### ISSUE TITLE
The repo doesn't contain any of the examples from the book besides the project structure.

### ISSUE THREAD

**Issue by salihkilic** [PacktPublishing/Hands-On-Software-Engineering-with-Python#3]
I came here looking for the BaseDaemon example written out in the book (in chapter 14, page 505) but there seem to be none. It seems like the examples stop from Chapter 7 onward, which is a shame because the interesting stuff starts there.

**Comment by salihkilic** [comment]
I just went to my account on packt to see if the code download there is any different, and it is. The examples do seem to be present in the zip for download, but not here on the github repo.

**Comment by gaurav-packt** [comment]
Hello @salihkilic the updated code files have been pushed, Please check and let us know if it works fine.
